# Generated by Django 2.2.5 on 2019-09-11 05:01

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arenas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stfips', models.CharField(max_length=2)),
                ('ctfips', models.CharField(max_length=5)),
                ('state', models.CharField(max_length=66)),
                ('county', models.CharField(max_length=66)),
                ('version', models.CharField(max_length=2)),
                ('shape_leng', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Districts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(max_length=2)),
                ('name', models.CharField(max_length=25)),
                ('party', models.CharField(max_length=19)),
                ('state', models.CharField(max_length=2)),
                ('stfips', models.CharField(max_length=2)),
                ('version', models.CharField(max_length=2)),
                ('shape_leng', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stfips', models.CharField(max_length=2)),
                ('state', models.CharField(max_length=66)),
                ('stpostal', models.CharField(max_length=2)),
                ('version', models.CharField(max_length=2)),
                ('dotregion', models.IntegerField()),
                ('shape_leng', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
    ]
